id: ActivityConfig.disableMotionActivityUpdates
source_file: background-geolocation-types/src/core/config/ActivityConfig.ts
signature: 'disableMotionActivityUpdates?: boolean;'
description: |-
  Disable the plugin requesting "Motion & Fitness" (ios) or "Physical Activity" (android >= 10) authorization from the User.

  Defaults to **`false`**.  Set to **`true`** to disable asking the user for this permission.

  __iOS__

  ![](https://dl.dropbox.com/s/v3qt7ry1k4b3iir/ios-motion-permission.png?dl=1)

  The plugin is **HIGHLY** optimized for motion-activity-updates.  If you **do** disable this, the plugin *will* drain more battery power.  You are **STRONGLY** advised against disabling this.  You should explain to your users with an appropriate `NSMotionUsageDescription` in your `Info.plist` file, for example:
  > "Motion activity detection increases battery efficiency by intelligently toggling location-tracking" off when your device is detected to be stationary.

  __Android__

  Android 10+ now requires run-time permission from the user for "Physical Activity".

  ![](https://dl.dropbox.com/s/6v4391oz592bdjg/android-permission-physical-activity.png?dl=1)

  Traditionally, the `background-geolocation` Android SDK has relied heavily upon the Motion API for determining when to toggle location-services on/off based upon whether the device is *moving* vs *stationary*.
  However, the Android SDK has a fallback "stationary geofence" mechanism just like iOS, the exit of which will cause the plugin to change to the *moving* state, toggle location-services and begin tracking.  This will, of course, require the device moves a distance of typically **200-500 meters** before tracking engages.  With the Motion API authorized, the Android SDK typically requires just **a few meters** of movement for tracking to engage.

  @example example-1
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.ready({
          disableMotionActivityUpdates: true
        });
