id: ActivityConfig.motionTriggerDelay
source_file: background-geolocation-types/src/core/config/ActivityConfig.ts
signature: 'motionTriggerDelay?: number;'
description: |-
  __`[Android only]`__  Optionally add a delay in milliseconds to trigger Android into the *moving* state when Motion API reports the device is moving (eg: `on_foot`, `in_vehicle`)

  This can help prevent false-positive motion-triggering when one moves about their home, for example.  Only if the Motion API stays in the *moving* state for `motionTriggerDelay` milliseconds will the plugin trigger into the *moving* state and begin tracking the location.
  If the Motion API returns to the `still` state before `motionTriggerDelay` times-out, the trigger to the *moving* state will be cancelled.

  @example example-1

  The following `logcat` shows an Android device detecting motion __`on_foot`__ but returning to __`still`__ before __`motionTriggerDelay`__ expires, cancelling the transition to the *moving* state (see `â° Cancel OneShot: MOTION_TRIGGER_DELAY`):

  __Logcat__
  ```bash
   04-08 10:58:03.419 TSLocationManager: â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   04-08 10:58:03.419 TSLocationManager: â•‘ Motion Transition Result
   04-08 10:58:03.419 TSLocationManager: â• â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   04-08 10:58:03.419 TSLocationManager: â•Ÿâ”€ ğŸ”´  EXIT: still
   04-08 10:58:03.419 TSLocationManager: â•Ÿâ”€ ğŸ¾  ENTER: on_foot
   04-08 10:58:03.419 TSLocationManager: â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   04-08 10:58:03.416 TSLocationManager:   â° Scheduled OneShot: MOTION_TRIGGER_DELAY in 30000ms
   .
   . <motionTriggerDelay timer started>
   .
   04-08 10:58:19.385 TSLocationManager: â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   04-08 10:58:19.385 TSLocationManager: â•‘ Motion Transition Result
   04-08 10:58:19.385 TSLocationManager: â• â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   04-08 10:58:19.385 TSLocationManager: â•Ÿâ”€ ğŸ”´  EXIT: on_foot
   04-08 10:58:19.385 TSLocationManager: â•Ÿâ”€ ğŸ¾  ENTER: still
   04-08 10:58:19.385 TSLocationManager: â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
   04-08 10:58:19.381 TSLocationManager: [c.t.l.s.TSScheduleManager cancelOneShot]
   04-08 10:58:19.381 TSLocationManager:   â° Cancel OneShot: MOTION_TRIGGER_DELAY <-- timer cancelled
  ```
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        // Delay Android motion-triggering by 30000ms
        BackgroundGeolocation.ready({
          motionTriggerDelay: 30000
        })
