id: ActivityConfig.triggerActivities
source_file: background-geolocation-types/src/core/config/ActivityConfig.ts
signature: 'triggerActivities?: TriggerActivity[] | TriggerActivity;'
description: |-
  Configures a comma-separated list of motion-activities which are allow to trigger location-tracking.

  __⚠️ Warning:__ Requires that the user grant your app the "*Motion/Health*" permission.


  These are the comma-delimited list of [activity-names](https://developers.google.com/android/reference/com/google/android/gms/location/DetectedActivity) returned by the `ActivityRecognition` API which will trigger a state-change from **stationary** to **moving**.  By default, the plugin will trigger on **any** of the **moving-states**:

  | Activity Name  |
  |----------------|
  | `in_vehicle`   |
  | `on_bicycle`   |
  | `on_foot`      |
  | `running`      |
  | `walking`      |

  See {@link TriggerActivity} for all allowed activity names.

  If you wish, you can configure the plugin to only engage the **moving** state for vehicles-only by providing just `"in_vehicle"`, for example.


  @example example-1
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        // Only trigger tracking for vehicles
        BackgroundGeolocation.ready({
          triggerActivities: "in_vehicle"
        );

        // Only trigger tracking for on_foot, walking and running
        BackgroundGeolocation.ready({
          triggerActivities: "on_foot, walking, running"
        );
