id: ActivityConfig.stopDetectionDelay
source_file: background-geolocation-types/src/core/config/ActivityConfig.ts
signature: 'stopDetectionDelay?: number;'
description: |-
  __`[iOS only]`__ Allows the iOS stop-detection system to be delayed from activating.

  Defaults to **`0`** (no delay).  Allows the stop-detection system to be delayed from activating.  When the stop-detection system *is* engaged, location-services will be temporarily turned **off** and only the accelerometer is monitored.  Stop-detection will only engage if this timer expires.  The timer is cancelled if any movement is detected before expiration.  If a value of **`0`** is specified, the stop-detection system will engage as soon as the device is detected to be stationary.

  You can experience the iOS stop-detection system at work by configuring {@link LoggerConfig.debug} __`true`__.  After the device stops moving (stopped at a traffic light, for example), the plugin will emit a *Lullabye* sound-effect and local-notifications about "Location-services: OFF / ON".

  __iOS Stop-detection timing__

  ![](https://dl.dropboxusercontent.com/s/ojjdfkmua15pskh/ios-stop-detection-timing.png?dl=1)
