id: AppConfig.enableHeadless
source_file: background-geolocation-types/src/core/config/AppConfig.ts
signature: 'enableHeadless?: boolean;'
description: |-
  __`[Android only]`__ Enables "Headless" operation allowing you to respond to events after you app has been terminated with [[stopOnTerminate]] __`false`__.

  Defaults to __`false`__.  In this Android terminated state, where only the plugin's foreground-service remains running, you can respond to all the plugin's events with your own callback.  For more information, see [[BackgroundGeolocation.registerHeadlessTask]].

  __‚ÑπÔ∏è Note:__
  - Requires {@link AppConfig.stopOnTerminate} __`false`__.
  - If you've configured {@link AppConfig.stopOnTerminate} __`false`__, {@link BackgroundGeolocation} will continue to record locations (and post them to your configured {@link HttpConfig.url}) *regardless of* __`enabledHeadless: true`__.  You should enable this option *only if* you wish to perform some custom work during the headless state (for example, posting a local notification).

  +__‚ÑπÔ∏è See also:__
  - üìò [Android Headless Mode](github:wiki/Android-Headless-Mode).
  - {@link BackgroundGeolocation.registerHeadlessTask}
