id: AppConfig.scheduleUseAlarmManager
source_file: background-geolocation-types/src/core/config/AppConfig.ts
signature: 'scheduleUseAlarmManager?: boolean;'
description: |-
  __Android only__ Force the Android scheduler to use `AlarmManager` (more precise) instead of `JobScheduler`.  Defaults to `false`.

  ```ts
  BackgroundGeolocation.ready({
    app: {
      schedule: ["1-7 09:00-17:00"],
      scheduleUseAlarmManager: true
    }
  });
  ```
