id: AppConfig.heartbeatInterval
source_file: background-geolocation-types/src/core/config/AppConfig.ts
signature: 'heartbeatInterval?: number;'
description: |-
  Controls the rate (in seconds) at which {@link BackgroundGeolocation.onHeartbeat}

  events will fire.

  **⚠️ Warning**

  - On **iOS**, {@link BackgroundGeolocation.onHeartbeat} will fire **only** when {@link AppConfig.preventSuspend} is set to `true`.
  - On **Android**, the *minimum* interval is **60 seconds**.
  - It is **not possible** to configure a `heartbeatInterval` faster than 60 seconds.

  @example example-1

  **ℹ️ See also**
  - {@link BackgroundGeolocation.onHeartbeat}
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.ready({
          app: {
            preventSuspend: true,
            heartbeatInterval: 60
          }
        });

        BackgroundGeolocation.onHeartbeat((event) => {
          console.log("[onHeartbeat]", event);

          // Optionally request a new location during heartbeat.
          BackgroundGeolocation.getCurrentPosition({
            samples: 1,
            persist: true
          }).then((location) => {
            console.log("[getCurrentPosition]", location);
          });
        });
