id: AuthorizationConfig.accessToken
source_file: background-geolocation-types/src/core/config/AuthorizationConfig.ts
signature: accessToken:string;
description: |-
  Authorization token (eg: [JWT](https://jwt.io/)) required for authorization by your server at {@link HttpConfig.url}.

  The SDK will automatically apply the configured `accessToken` to each HTTP request's `Authorization` header, eg:

  `"Authorization": "Bearer XXX.YYY.ZZZ"`

  You do **not** need to manually configure {@link HttpConfig.headers} with the `Authorization` parameter.  It is all **automatic**.
