id: GeoConfig.showsBackgroundLocationIndicator
source_file: background-geolocation-types/src/core/config/GeoConfig.ts
signature: 'showsBackgroundLocationIndicator?: boolean;'
description: |-
  [__iOS Only__] A Boolean indicating whether the status bar changes its appearance when an app uses location services in the background with `Always` authorization.

  The default value of this property is `true`. The background location usage indicator is a blue bar or a blue pill in the status bar on iOS; on watchOS the indicator is a small icon. Users can tap the indicator to return to your app.

  This property affects only apps that received `Always` authorization. When such an app moves to the background, the system uses this property to determine whether to change the status bar appearance to indicate that location services are in use. Set this value to true to maintain transparency with the user.

  For apps with When In Use authorization, the system changes the appearance of the status bar when the app uses location services in the background.
