id: GeoConfig.pausesLocationUpdatesAutomatically
source_file: background-geolocation-types/src/core/config/GeoConfig.ts
signature: 'pausesLocationUpdatesAutomatically?: boolean;'
description: |-
  **`[iOS only]`** Prevent the iOS location API from *ever* automatically turning off.

  **⚠️ WARNING:**
  This option should almost always remain `undefined`.
  Only set this if you know **exactly** what you're doing.

  By default, the SDK automatically turns **off** iOS location-services when the
  device remains stationary for {@link stopTimeout} minutes.

  When this option is explicitly set to `false`, location-services will **never**
  be turned off. In this mode:

  - {@link ActivityConfig.disableStopDetection} will automatically be forced to `true`
  - You are responsible for disabling tracking when you no longer need it
  - This can have **severe battery-drain implications**
  - {@link AppConfig.preventSuspend} will no longer function

  This option exists only for highly specialized use-cases and should generally
  **not** be used in production applications.
