id: GeoConfig.geofenceProximityRadius
source_file: background-geolocation-types/src/core/config/GeoConfig.ts
signature: 'geofenceProximityRadius?: number;'
description: |-
  Defines the radius (in meters) around the device used to query for geofences
  that should be actively monitored.

  The default â€” and **minimum** â€” value is **1000 meters**.

  Mobile platforms allow only a limited number of concurrently monitored geofences
  (**iOS: 20**, **Android: ~100**).

  The SDK removes this limitation by allowing you to register **any number of geofences**
  (thousands even). It stores them in its internal database and performs efficient
  spatial queries to determine which subset of geofences should be activated based on
  the deviceâ€™s current position.

  As the device moves, this radius determines when the monitored geofence set changes,
  firing {@link BackgroundGeolocation.onGeofencesChange}.

  **See also**
  - ðŸ“˜ {@link Geofence | Geofencing Guide}
  - [Animation of this behavior](https://www.transistorsoft.com/shop/products/assets/images/background-geolocation-infinite-geofencing.gif)

  ![](https://dl.dropboxusercontent.com/s/7sggka4vcbrokwt/geofenceProximityRadius_iphone6_spacegrey_portrait.png?dl=1)
