id: GeoConfig.desiredAccuracy
source_file: background-geolocation-types/src/core/config/GeoConfig.ts
signature: 'desiredAccuracy?: DesiredAccuracy;'
description: |-
  Specify the desired-accuracy of the geolocation system.

  The following constants are defined upon the {@link BackgroundGeolocation} class:

  | Name                                                  | Location Providers                   | Description                     |
  |-------------------------------------------------------|--------------------------------------|---------------------------------|
  | {@link DesiredAccuracy.Navigation} | (**iOS only**) GPS + Wifi + Cellular | Highest power; highest accuracy |
  | {@link DesiredAccuracy.High}       | GPS + Wifi + Cellular                | Highest power; highest accuracy |
  | {@link DesiredAccuracy.Medium}     | Wifi + Cellular                      | Medium power; Medium accuracy;  |
  | {@link DesiredAccuracy.Low}        | Wifi (low power) + Cellular          | Lower power; No GPS             |
  | {@link DesiredAccuracy.VeryLow}   | Cellular only                        | Lowest power; lowest accuracy   |
  | {@link DesiredAccuracy.Lowest}     | (**iOS only**)                       | Lowest power; lowest accuracy   |

  ### ⚠️ Note:
  -  Only **`DESIRED_ACCURACY_HIGH`** uses GPS.  `speed`, `heading` and `altitude` are available only from GPS.

  @example example-1
  For platform-specific information about location accuracy, see the corresponding API docs:
  - [Android](https://developer.android.com/reference/com/google/android/gms/location/LocationRequest.html#PRIORITY_BALANCED_POWER_ACCURACY)
  - [iOS](https://developer.apple.com/reference/corelocation/cllocationmanager/1423836-desiredaccuracy?language=objc)
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeoloction.ready({
          desiredAccuracy: BackgroundGeolocation.DesiredAccuracy.High,
        });
