id: GeoConfig.locationUpdateInterval
source_file: background-geolocation-types/src/core/config/GeoConfig.ts
signature: 'locationUpdateInterval?: number;'
description: |-
  **[Android only]** Desired interval for *active* location updates, in milliseconds.

  **⚠️ Important**
  - To use `locationUpdateInterval`, you **must** also set
    {@link distanceFilter} to `0`.
    If `distanceFilter` > 0, it **overrides** this interval.

  This value tells Android how frequently your app *wants* location updates.
  The system will try to honor it but may deliver updates:
  - slower (no providers available),
  - faster (another app requests faster updates),
  - or not at all (permission or system constraints).

  Apps with only *coarse* location permission may have this interval silently throttled.

  @example example-1

  **ℹ️ See also**
  - Android’s `LocationRequest.setInterval`:
    https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest.html#setInterval(long)
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.ready({
          geolocation: {
            distanceFilter: 0,           // Required — otherwise this field is ignored.
            locationUpdateInterval: 5000 // Request a fix every ~5 seconds
          }
        });
