id: GeoConfig.disableLocationAuthorizationAlert
source_file: background-geolocation-types/src/core/config/GeoConfig.ts
signature: 'disableLocationAuthorizationAlert?: boolean;'
description: |-
  Disables automatic authorization alert when plugin detects the user has disabled location authorization.

  You will be responsible for handling disabled location authorization by listening to the {@link BackgroundGeolocation.onProviderChange} event.

  By default, the plugin automatically shows a native alert to the user when location-services are disabled, directing them to the settings screen.  If you **do not** desire this automated behavior, set `disableLocationAuthorizationAlert: true`.

  __iOS__

  The iOS alert dialog text elements can be configured via {@link locationAuthorizationAlert} and {@link locationAuthorizationRequest}.

  ![](https://dl.dropbox.com/s/wk66ave2mzq6m6a/ios-locationAuthorizationAlert.jpg?dl=1)

  __Android__

  Android can detect when the user has configured the device's *Settings->Location* in a manner that does not match your location request (eg: {@link desiredAccuracy}).  For example, if the user configures *Settings->Location->Mode* with *Battery Saving* (ie: Wifi only) but you've specifically requested {@link DesiredAccuracy.High} (ie: GPS), Android will show a dialog asking the user to confirm the desired changes.  If the user clicks `[OK]`, the OS will automcatically modify the Device settings.

  ![](https://dl.dropbox.com/scl/fi/t7bwdrmogr26rcmrbemkt/android-location-resolution-dialog.png?rlkey=won88t8xo5zcei7ktmurebb5t&dl=1)

  This automated Android dialog will be shown in the following cases:
  - {@link BackgroundGeolocation.onProviderChange}
  - {@link BackgroundGeolocation.start}
  - {@link BackgroundGeolocation.requestPermission}

  @example example-1
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.onProviderChange((event) => {
          console.log("[onProviderChange] ", event);

          if (!provider.enabled) {
            alert("Please enable location services");
          }
        });

        BackgroundGeolocation.ready({
          disableLocationAuthorizationAlert: true
        });
