id: GeoConfig.stopTimeout
source_file: background-geolocation-types/src/core/config/GeoConfig.ts
signature: 'stopTimeout?: number;'
description: |-
  Minutes to wait in *moving* state with no movement before considering the device *stationary*.

  Defaults to `5` minutes.  When in the *moving* state, specifies the number of minutes to wait before turning off location-services and
  transitioning to *stationary* state after the ActivityRecognition System detects the device is `STILL`.  An example use-case for this
  configuration is to delay GPS OFF while in a car waiting at a traffic light.

  :warning: Setting a very long `stopTimeout` will cause the device's location API to remain ON while the device is potentially motionless for extended periods, which may have a significant impact on battery life.  It depends upon your use-case.

  ### ‚ÑπÔ∏è See also:
  - {@link BackgroundGeolocation.onMotionChange}
  - üìò [Philosophy of Operation](github:wiki/Philosophy-of-Operation)
