id: GeoConfig.stopOnStationary
source_file: background-geolocation-types/src/core/config/GeoConfig.ts
signature: 'stopOnStationary?: boolean;'
description: |-
  Automatically {@link BackgroundGeolocation.stop} when the {@link stopTimeout} elapses.

  The plugin can optionally automatically stop tracking when the {@link stopTimeout} timer elapses.  For example, when the plugin
  first fires {@link BackgroundGeolocation.onMotionChange} into the *moving* state, the next time an *onMotionChange* event occurs
  into the *stationary* state, the plugin will have automatically called {@link BackgroundGeolocation.stop} upon itself.

  ⚠️ `stopOnStationary` will **only** occur due to {@link stopTimeout} timer elapse.  It will **not** occur by manually executing
  {@link BackgroundGeolocation.changePace} __`false`__.

  @example example-1
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.ready({
          stopOnStationary: true,
          isMoving: true
        }, (state) => {
          BackgroundGeolocation.start();
        });
