id: GeoConfig.locationAuthorizationAlert
source_file: background-geolocation-types/src/core/config/GeoConfig.ts
signature: 'locationAuthorizationAlert?: Record<string, any>;'
description: |-
  **[iOS only]** Customize the text displayed in the SDK’s
  location-authorization alert dialog.

  When {@link locationAuthorizationRequest} is configured as
  `"Always"` or `"WhenInUse"` and the user subsequently *downgrades* or disables
  location permission in iOS Settings, the SDK presents an alert directing the
  user back to the **Settings** screen.

  `locationAuthorizationAlert` lets you override all of the strings used in that
  alert. You must supply an object matching {@link locationAuthorizationAlert}.

  ![](https://dl.dropboxusercontent.com/s/wyoaf16buwsw7ed/docs-locationAuthorizationAlert.jpg?dl=1)

  @example example-1

  **⚠️ Warning**

  If you provide `locationAuthorizationAlert`, you **must** supply **all**
  {@link locationAuthorizationAlert} fields — not just a subset.
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.ready({
          geolocation: {
            locationAuthorizationAlert: {
              titleWhenNotEnabled: "Location services are not enabled",
              titleWhenOff: "Location services are OFF",
              instructions:
                "Please enable 'Always' in Location Services to allow background tracking.",
              cancelButton: "Cancel",
              settingsButton: "Open Settings"
            }
          }
        });
