id: HttpConfig.autoSync
source_file: background-geolocation-types/src/core/config/HttpConfig.ts
signature: 'autoSync?: boolean;'
description: |-
  Immediately upload each recorded location to your configured {@link url}.

  Defaults to **`true`**.

  When `autoSync` is enabled and a {@link url} is provided, the SDK
  will attempt to upload each location **as soon as it is recorded**.

  If you set `autoSync: false`, you must manually call
  {@link BackgroundGeolocation.sync} to initiate uploads.
  Regardless of `autoSync`, *all* recorded locations are persisted in the
  SDKâ€™s internal SQLite database until successfully delivered.

  __Note:__ The queue continues to grow until you call {@link BackgroundGeolocation.sync} or until uploads succeed.

  **See also**
  - {@link autoSyncThreshold}
  - {@link batchSync}
  - {@link maxBatchSize}
  - HTTP Guide at {@link HttpConfig}
