id: HttpConfig.batchSync
source_file: background-geolocation-types/src/core/config/HttpConfig.ts
signature: 'batchSync?: boolean;'
description: |-
  Upload **multiple locations** to your {@link url} in a single HTTP request.

  Defaults to **`false`**.
  When set to **`true`**, the SDK will bundle **all currently queued locations** in
  the native SQLite database and upload them together in **one** HTTP request.

  When `batchSync` is **`false`**, the HTTP service performs **one request per
  location**, which can increase battery and network usage.

  Batching is often used together with {@link autoSyncThreshold} to
  reduce upload frequency and conserve power.

  **See also**
  - {@link url}
  - {@link autoSync}
  - {@link autoSyncThreshold}
  - **HTTP Guide** at {@link HttpConfig}
