id: HttpConfig.method
source_file: background-geolocation-types/src/core/config/HttpConfig.ts
signature: 'method?: HttpMethod;'
description: |-
  The HTTP method used when uploading locations to your configured {@link url}.

  Defaults to **`POST`**.

  Valid values: **`POST`**, **`PUT`**, **`OPTIONS`**.

  @example example-1
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.ready({
          http: {
            url: "https://my-server.com/locations",
            method: "PUT"
          }
        });
