id: LoggerConfig.logLevel
source_file: background-geolocation-types/src/core/config/LoggerConfig.ts
signature: 'logLevel?: LogLevel;'
description: |-
  Controls the volume of recorded events in the plugin's logging database.

  {@link BackgroundGeolocation} contains powerful logging features. By default,
  the plugin starts with {@link LogLevel.Off},
  storing {@link LoggerConfig.logMaxDays | logMaxDays} days worth of logs in its
  internal SQLite database (default: `3`).

  The following log levels are defined as constants on {@link BackgroundGeolocation}:

  | Label                   | Value                              |
  |-------------------------|------------------------------------|
  | {@link LogLevel.Off}   | `0` |
  | {@link LogLevel.Error} | `1` |
  | {@link LogLevel.Warning} | `2` |
  | {@link LogLevel.Info}  | `3` |
  | {@link LogLevel.Debug} | `4` |
  | {@link LogLevel.Verbose} | `5` |

  __Example log data__

  ```text
  09-19 11:12:18.716 â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  09-19 11:12:18.716 â•‘ BackgroundGeolocation Service started
  09-19 11:12:18.716 â• â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  09-19 11:12:18.723 [c.t.l.BackgroundGeolocationService d]
  09-19 11:12:18.723   âœ…  Started in foreground
  09-19 11:12:18.737 [c.t.l.ActivityRecognitionService a]
  09-19 11:12:18.737   ğŸ¾  Start activity updates: 10000
  09-19 11:12:18.761 [c.t.l.BackgroundGeolocationService k]
  09-19 11:12:18.761   ğŸ”´  Stop heartbeat
  09-19 11:12:18.768 [c.t.l.BackgroundGeolocationService a]
  09-19 11:12:18.768   ğŸ¾  Start heartbeat (60)
  09-19 11:12:18.778 [c.t.l.BackgroundGeolocationService a]
  09-19 11:12:18.778   ğŸ”µ  setPace: null â†’ false
  09-19 11:12:18.781 [c.t.l.adapter.TSConfig c] â„¹ï¸   Persist config
  09-19 11:12:18.794 [c.t.locationmanager.util.b a]
  09-19 11:12:18.794   â„¹ï¸  LocationAuthorization: Permission granted
  09-19 11:12:18.842 [c.t.l.http.HttpService flush]
  09-19 11:12:18.842 â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  09-19 11:12:18.842 â•‘ HTTP Service
  09-19 11:12:18.842 â• â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  09-19 11:12:19.000 [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
  09-19 11:12:21.314 [c.t.l.l.SingleLocationRequest$2 onLocationResult]
  09-19 11:12:21.314 â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  09-19 11:12:21.314 â•‘ SingleLocationRequest: 1
  09-19 11:12:21.314 â• â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  09-19 11:12:21.314 â•Ÿâ”€ ğŸ“  Location[fused 45.519239,-73.617058 hAcc=15]999923706055 vAcc=2 sAcc=??? bAcc=???
  09-19 11:12:21.327 [c.t.l.l.TSLocationManager onSingleLocationResult]
  09-19 11:12:21.327   ğŸ”µ  Acquired motionchange position, isMoving: false
  09-19 11:12:21.342 [c.t.l.l.TSLocationManager a] 15.243
  09-19 11:12:21.405 [c.t.locationmanager.data.a.c persist]
  09-19 11:12:21.405   âœ…  INSERT: bca5acc8-e358-4d8f-827f-b8c0d556b7bb
  09-19 11:12:21.423 [c.t.l.http.HttpService flush]
  09-19 11:12:21.423 â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  09-19 11:12:21.423 â•‘ HTTP Service
  09-19 11:12:21.423 â• â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  09-19 11:12:21.446 [c.t.locationmanager.data.a.c first]
  09-19 11:12:21.446   âœ…  Locked 1 records
  09-19 11:12:21.454 [c.t.l.http.HttpService a]
  09-19 11:12:21.454   ğŸ”µ  HTTP POST: bca5acc8-e358-4d8f-827f-b8c0d556b7bb
  09-19 11:12:22.083 [c.t.l.http.HttpService$a onResponse]
  09-19 11:12:22.083   ğŸ”µ  Response: 200
  09-19 11:12:22.100 [c.t.locationmanager.data.a.c destroy]
  09-19 11:12:22.100   âœ…  DESTROY: bca5acc8-e358-4d8f-827f-b8c0d556b7bb
  09-19 11:12:55.226 [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
  ```

  @example example-1

  __See also__
  - {@link logMaxDays}
  - {@link Logger.getLog}
  - {@link Logger.emailLog}
  - {@link Logger.destroyLog}

  __âš ï¸ Warning__
  When submitting your app to production, configure `logLevel` appropriately
  (for example, {@link LogLevel.Error}),
  since logs can grow to several megabytes over {@link LoggerConfig.logMaxDays | logMaxDays}.
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.ready({
          logger: {
            logLevel: LogLevel.Verbose
          },
        });
