id: LoggerConfig.logMaxDays
source_file: background-geolocation-types/src/core/config/LoggerConfig.ts
signature: 'logMaxDays?: number;'
description: |-
  Maximum number of days to persist a log-entry in database.

  Defaults to **`3`** days.

  @example example-1
   **See also:**
  - {@link logLevel}
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.ready({
          logger: {
            logMaxDays: 3
          }
        });
