id: NotificationConfig.priority
source_file: background-geolocation-types/src/core/config/NotificationConfig.ts
signature: 'priority?: NotificationPriority;'
description: |-
  __Android notification priority__

  Android requires a persistent foreground-service notification.
  The `priority` option controls both:

  - The **order** of the notification in the system shade.
  - The **position/visibility** of the small status-bar icon.

  The following values are defined as static constants on
  {@link BackgroundGeolocation}:

  | Value                                                     | Description                                                                                              |
  |-----------------------------------------------------------|----------------------------------------------------------------------------------------------------------|
  | {@link NotificationPriority.Default} | Weighted toward the top of the notification list; status-bar icon left-aligned.                          |
  | {@link NotificationPriority.High}    | Strongly weighted to the top; icon strongly left-aligned.                                                |
  | {@link NotificationPriority.Low}     | Weighted toward the bottom; icon right-aligned.                                                          |
  | {@link NotificationPriority.Max}     | Equivalent to `NOTIFICATION_PRIORITY_HIGH`.                                                              |
  | {@link NotificationPriority.Min}     | Strongly weighted to the bottom; icon hidden.                                                             |

  @example example-1
examples:
  example-1:
    title: Example 1
    code:
      ts: |-
        BackgroundGeolocation.ready({
          app: {
            foregroundService: true,
            notification: {
              priority: NotificationPriority.High
            }
          }
        });
