id: NotificationConfig.strings
source_file: background-geolocation-types/src/core/config/NotificationConfig.ts
signature: 'strings?: Record<string, string>;'
description: |-
  Custom strings to render into `<TextView />` elements of a custom notification [[layout]].

  ℹ️ See [Android Custom Notification Layout](github:wiki/Android-Custom-Notification-Layout) for setup instructions.

  You can declare your own custom `<TextView />` elements and render data into them using the `notification.strings` parameter.

  @example example-1

  You can provide data to your custom elements using the [[strings]] configuration parameter:

  @example example-2
examples:
  example-1:
    title: Example 1
    code:
      xml: |-
        <TextView
            android:id="@+id/myCustomElement"  // <-- myCustomElement
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="notificationTitle" />
  example-2:
    title: Example 2
    code:
      ts: |-
        BackgroundGeolocation.ready({
          app: {
            notification: {
              strings: {
                myCustomElement: "My Custom Element Text"
              }
            }
          }
        });
