id: NotificationConfig.sticky
source_file: background-geolocation-types/src/core/config/NotificationConfig.ts
signature: 'sticky?: boolean;'
description: |-
  Configure the Android Foreground Service icon and notification to be displayed __always__.  Defaults to `false`.

  The default behaviour is for the notification to be shown only while the SDK detects the device to be *moving*.
  Some developers desire to provide full-disclosure to their users when the SDK has been enabled.
