id: NotificationConfig.color
source_file: background-geolocation-types/src/core/config/NotificationConfig.ts
signature: 'color?: string;'
description: |-
  Configure the *color* of the persistent notification icon in the Notification Bar.

  Defaults to `null`.  Android requires a persistent notification for foreground-services.  This will configure the **color** of the notification **icon** (API >= 21).

  Supported formats are:
  - `#RRGGBB`
  - `#AARRGGBB`
