id: NotificationConfig.actions
source_file: background-geolocation-types/src/core/config/NotificationConfig.ts
signature: 'actions?: string[];'
description: |-
  Declare click listeners for `<Button />` elements of a custom notification {@link layout}.

  ![](https://dl.dropbox.com/s/whcb6q1gxxdk9t1/android-foreground-notification-transistor.png?dl=1)

  ℹ️ See [Android Custom Notification Layout](github:wiki/Android-Custom-Notification-Layout) for setup instructions.

  You can declare custom Android `<Button />` elements in your layout XML and
  register click listeners for them using the {@link actions} parameter.

  __Example: Custom `<Button />` element__

  ```xml
  <Button
      android:id="@+id/notificationButtonPause"  <!-- notificationButtonPause -->
      style="@style/Widget.AppCompat.Button.Small"
      android:layout_width="60dp"
      android:layout_height="40dp"
      android:text="Foo" />
  ```

  __Example: Register button listeners__

  ```ts
  BackgroundGeolocation.ready({
    app: {
      notification: {
        actions: [
          "notificationButtonPause"   // <-- register button listeners
        ]
      }
    }
  });

  // Listen to custom button clicks:
  BackgroundGeolocation.onNotificationAction((buttonId) => {
    console.log("[onNotificationAction] - ", buttonId);
    switch (buttonId) {
      case "notificationButtonPause":
        BackgroundGeolocation.changePace(false);
        break;
      // ...
    }
  });
  ```
