id: PersistenceConfig.extras
source_file: background-geolocation-types/src/core/config/PersistenceConfig.ts
signature: 'extras?: Record<string, any>;'
description: |-
  Optional arbitrary key/value pairs merged into **each** recorded location.

  These values are persisted and included in all HTTP uploads, making them
  ideal for attaching contextual metadata such as `user_id`, `route_id`,
  or `session_id`.

  __See also:__
  - ðŸ“˜ {@link HttpEvent | HTTP Guide}

  __Example:__
  ```typescript
  BackgroundGeolocation.ready({
    http: {
      url: "https://my-server.com/locations",
      params: {
        device_id: "abc123"  // <-- appended to root JSON of each POST request
      }
    },
    persistence: {
      extras: {
        route_id: 1234       // <-- merged onto each location record
      }
    }
  });
  ```

  __Incoming request at your server:__
  ```json
  POST /locations
  {
    "device_id": "abc123",        // from `params`
    "location": {
      "coords": {
        "latitude": 45.51927004945047,
        "longitude": -73.61650072045029
      },
      "extras": {                 // from `extras`
        "route_id": 1234
      }
    }
  }
  ```
