id: PersistenceConfig.persistMode
source_file: background-geolocation-types/src/core/config/PersistenceConfig.ts
signature: 'persistMode?: PersistMode;'
description: |-
  Controls which event types the SDK will persist into its internal SQLite
  database: locations, geofences, or both.

  All recorded events are always delivered to their live callbacks
  ({@link BackgroundGeolocation.onLocation} and
  {@link BackgroundGeolocation.onGeofence}). This option only determines
  what is written to persistent storage. Events that are *not* persisted are
  also *not* eligible for HTTP uploads via {@link HttpConfig.url}.

  | Name                                                     | Description                       |
  |----------------------------------------------------------|-----------------------------------|
  | {@link PersistMode.All}           | **Default** â€” persist both geofence and location events. |
  | {@link PersistMode.Location}      | Persist **location** events only.                        |
  | {@link PersistMode.Geofence}      | Persist **geofence** events only.                        |
  | {@link PersistMode.None}          | Persist **nothing**.                                     |

  __Warning__:

  This option is intended for specialized cases. For example, if you need
  continuous location tracking via {@link BackgroundGeolocation.start} but
  only want to *store* geofence events, configure:
  `persistMode: PersistMode.Geofence`.
