id: PersistenceConfig.disableProviderChangeRecord
source_file: background-geolocation-types/src/core/config/PersistenceConfig.ts
signature: 'disableProviderChangeRecord?: boolean;'
description: |-
  __Android-only__
  Disable the automatic insertion of a synthetic “provider-change” location
  into the SDK’s SQLite database (and its subsequent HTTP upload).

  By default, when an {@link BackgroundGeolocation.onProviderChange} event fires, the Android SDK
  records a special location documenting *when* and *where* the device’s
  location-services state changed (e.g., GPS disabled).
  This behavior historically existed to support platforms with limited or
  unreliable Headless Task implementations (e.g., Cordova, Capacitor).

  Some developers have strict server-side JSON schemas or use
  {@link locationTemplate}, making it impossible to accept the automatically
  injected `provider` field. In these cases, set this flag to `true`.

  ![](https://www.dropbox.com/s/ljacoquuuv5sd5r/disableProviderChangeRecord.png?dl=1)

  __Example:__
  ```typescript
  BackgroundGeolocation.ready({
    persistence: {
      disableProviderChangeRecord: true
   }
  });
  ```
